project:
  type: website
  output-dir: docs
  
website:
  title: "Sameera Viswakula"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - workshops.qmd
      - software.qmd
    tools:
      - icon: house
        href: https://www.res.cmb.ac.lk/statistics/sameera-viswakula/
      - icon: linkedin
        href: https://www.linkedin.com/in/sameeraviswakula/
      - icon: github
        href: https://github.com/sameeranc/academic
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Sameera Viswakula"

format:
  html:
    theme: 
      dark: slate
    toc: true
    page-layout: full
    
editor: visual

keywords:
  - Viswakula
  - Sameera
  - Sameera Viswakula
