---
title: "Software"
---

## United States Copyright

• R code for modeling inflated count data: an EM algorithmic approach. Copyright Number: TXu002192850 (2020) Viswakula, Sameera Dhananjaya and Fernando, Srinal.

## R Shiny Apps

1. An interactive R Shiny application for creating customizable maps of Sri Lanka. Users can select specific provinces, districts, or Grama Niladhari divisions and export high-quality maps in PNG, PDF, or dynamic HTML formats. <https://sameera-viswakula.shinyapps.io/SL_Map_App/>
2. Shiny app for converting an image to an R plot. It can also be used to draw and creat a 2D dataset with a trends, outliers etc. Check it out here. <https://sameera-viswakula.shinyapps.io/Convert_or_draw_your_plot/>

## Software Released

1.  RNASSA 2.0: RNA Secondary Structure Analysis (Version 2.0.121208). Leung, M.-Y., Mohl, J., Licon, A., Viswakula, S., Kelley, P., Araiza, R., Kodimala, V., Vegesna, R., Saldivar, L., Yehadego, D., Cardenas, G., Vest, E.,Fuentes, O., Taufer, M., Johnson, K. L., (2012).
2.  Segmenta 2.0: A Bioinformatics Tool for RNA Segmentation (Version 2.0.121208). Leung, M.-Y., Viswakula, S., Kodimala, V., Yehadego, D., Vegesna, R., Taufer, M., Johnson, K. L., (2012).
